{"name": "test_get_auth_with_errpassword", "status": "passed", "description": "测试输入错误的password获取access_token", "attachments": [{"name": "LoginForAccessTokenApiLoginTokenPostAPI", "source": "221fea95-2411-4696-9240-a3ec0bc8a66e-attachment.json", "type": "application/json"}, {"name": "log", "source": "3899e4e9-1a0e-4bd6-a101-3c51acfa0866-attachment.txt", "type": "text/plain"}], "start": 1758184950082, "stop": 1758184950097, "uuid": "5a3bb663-a1f2-4971-8df2-efb890f9c56d", "historyId": "b17f5c6455c02bd06e10535474b56c52", "testCaseId": "53cdce8c0755db7990a2f74be0704d04", "fullName": "testcases.test_scenario.auth.test_auth#test_get_auth_with_errpassword", "labels": [{"name": "tag", "value": "auth"}, {"name": "parentSuite", "value": "testcases.test_scenario.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "22120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_scenario.auth.test_auth"}]}